---
title: "Penguin data wrangling & examples"
author: "Allison Horst"
date: "6/5/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(here)
knitr::opts_chunk$set(echo = TRUE)
```

### Get the data

```{r}
penguins <- read_csv(here("data","penguins_lter.csv")) %>% 
  clean_names()
```
### Create simplified subset 

Wrangling to create the simplified data subset, **penguins_size.csv**.

```{r}
penguin_sub <- penguins %>% 
  mutate(species_short = word(species, 1)) %>% 
  select(species_short, 
         island, 
         culmen_length_mm, 
         culmen_depth_mm, 
         flipper_length_mm, 
         body_mass_g, 
         sex)

write_csv(penguin_sub, here("data","penguins_size.csv"))
```

### Example graphs

#### Penguin mass vs. flipper length:

```{r}
mass_flipper <- ggplot(data = penguin_sub, 
                       aes(x = flipper_length_mm,
                           y = body_mass_g)) +
  geom_point(aes(color = species_short, 
                 shape = species_short),
             size = 3,
             alpha = 0.8) +
  theme_minimal() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Penguin size, Palmer Station LTER",
       subtitle = "Flipper length and body mass for Adelie, Chinstrap and Gentoo Penguins",
       x = "Flipper length (mm)",
       y = "Body mass (g)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme(legend.position = c(0.2, 0.7),
        legend.background = element_rect(fill = "white", color = NA),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

mass_flipper

ggsave(here("figures","mass_flipper.png"), width = 8, height = 5)
```

#### Flipper length vs. culmen length

```{r}
flipper_culmen <- ggplot(data = penguin_sub,
                         aes(x = flipper_length_mm,
                             y = culmen_length_mm)) +
  geom_point(aes(color = species_short, 
                 shape = species_short),
             size = 3,
             alpha = 0.8) +
  theme_minimal() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Flipper and culmen length",
       subtitle = "Dimensions for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Flipper length (mm)",
       y = "Culmen length (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme(legend.position = c(0.85, 0.15),
        legend.background = element_rect(fill = "white", color = NA),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

flipper_culmen

ggsave(here("figures","flipper_culmen.png"), width = 8, height = 5)

```
#### Flipper length vs. culmen length

```{r}
culmen_len_dep <- ggplot(data = penguin_sub,
                         aes(x = culmen_length_mm,
                             y = culmen_depth_mm,
                             group = species_short)) +
  geom_point(aes(color = species_short, 
                 shape = species_short),
             size = 3,
             alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE, aes(color = species_short)) +
  theme_minimal() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Penguin culmen dimensions",
       subtitle = "Culmen length and depth for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
       x = "Culmen length (mm)",
       y = "Culmen depth (mm)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme(legend.position = c(0.85, 0.15),
        legend.background = element_rect(fill = "white", color = NA),
        plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot")

culmen_len_dep

ggsave(here("figures","culmen_len_dep.png"), width = 8, height = 5)

```

#### Simpson's paradox, omitting species in graph above:  

```{r}
culmen_no_species <- ggplot(data = penguin_sub,
                         aes(x = culmen_length_mm,
                             y = culmen_depth_mm)) +
  geom_point() +
  theme_minimal() +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  labs(title = "Penguin culmen dimensions (omit species)",
       subtitle = "Palmer Station LTER",
       x = "Culmen length (mm)",
       y = "Culmen depth (mm)") +
  theme(plot.title.position = "plot",
        plot.caption = element_text(hjust = 0, face= "italic"),
        plot.caption.position = "plot") +
  geom_smooth(method = "lm", se = FALSE, color = "gray50")

culmen_no_species

ggsave(here("figures", "culmen_no_species.png"), width = 8, height = 5)

```

